#!/usr/bin/python3

"""
    Test RestAPI

    OpenAPI spec version: 1.0.0
    Contact: vbondyrev@gmail.com
    Generated by: https://github.com/vbondyrev/RentModel-RestAPI
"""

from app.views import app

if __name__ == '__main__':
    app.run('0.0.0.0')
